// <auto-generated />
namespace Leem.Testify.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TestProjectAssemblyName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestProjectAssemblyName));
        
        string IMigrationMetadata.Id
        {
            get { return "201310170230060_TestProjectAssemblyName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
