// <auto-generated />
namespace Leem.Testify.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_summaries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_summaries));
        
        string IMigrationMetadata.Id
        {
            get { return "201403292244049_Added_summaries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
