// <auto-generated />
namespace Leem.Testify.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UnitTestCoveredLinePoco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnitTestCoveredLinePoco));
        
        string IMigrationMetadata.Id
        {
            get { return "201502011414291_UnitTestCoveredLinePoco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
