//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leem.Testify
{
    using System;
    using System.Collections.Generic;
    using Leem.Testify.Poco;
    
    public partial class CoveredLine
    {
        public CoveredLine()
        {
            this.TrackedMethods = new HashSet<TrackedMethod>();
            this.UnitTests = new HashSet<UnitTest>();
        }
    
        public string Module { get; set; }
        public string Class { get; set; }
        public string Method { get; set; }
        public int LineNumber { get; set; }
        public bool IsCode { get; set; }
        public bool IsCovered { get; set; }
        public int CoveredLineId { get; set; }
        public bool IsSuccessful { get; set; }
        public int UnitTestId { get; set; }
    
        public virtual ICollection<TrackedMethod> TrackedMethods { get; set; }
        public virtual ICollection<UnitTest> UnitTests { get; set; }
    }
}
