// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TodoGlyphTest</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Lactose
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    #region Base entity class
    public partial class EntityBase<T>
    {

        private static System.Xml.Serialization.XmlSerializer serializer;

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
                }
                return serializer;
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current EntityBase object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize()
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes workflow markup into an EntityBase object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out T obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static T Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current EntityBase object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual void SaveToFile(string fileName)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an EntityBase object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out T obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static T LoadFromFile(string fileName)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                //file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion

        #region Clone method
        /// <summary>
        /// Create a clone of this T object
        /// </summary>
        public virtual T Clone()
        {
            return ((T)(this.MemberwiseClone()));
        }
        #endregion
    }
    #endregion

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CoverageSession")]
    public partial class CoverageSession : EntityBase<CoverageSession>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private Summary summaryField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<Module> modulesField;

        /// <summary>
        /// CoverageSession class constructor
        /// </summary>
        public CoverageSession()
        {
            this.modulesField = new List<Module>();
            this.summaryField = new Summary();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Summary Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Module", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<Module> Modules
        {
            get
            {
                return this.modulesField;
            }
            set
            {
                this.modulesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Summary")]
    public partial class Summary : EntityBase<Summary>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float sequenceCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool sequenceCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float branchCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool branchCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int maxCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool maxCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int minCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool minCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sequenceCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sequenceCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float branchCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool branchCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool maxCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool minCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Module")]
    public partial class Module : EntityBase<Module>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleSummary summaryField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string fullNameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string moduleNameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleFiles filesField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClasses classesField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleTrackedMethod> trackedMethodsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string skippedDueToField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string hashField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string skippedDueTo { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hash { get; set; }


        /// <summary>
        /// Module class constructor
        /// </summary>
        public Module()
        {
            this.trackedMethodsField = new List<ModuleTrackedMethod>();
            this.classesField = new ModuleClasses();
            this.filesField = new ModuleFiles();
            this.summaryField = new ModuleSummary();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleSummary Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleFiles Files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClasses Classes
        {
            get
            {
                return this.classesField;
            }
            set
            {
                this.classesField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TrackedMethod", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleTrackedMethod> TrackedMethods
        {
            get
            {
                return this.trackedMethodsField;
            }
            set
            {
                this.trackedMethodsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleSummary")]
    public partial class ModuleSummary : EntityBase<ModuleSummary>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float sequenceCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool sequenceCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float branchCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool branchCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int maxCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool maxCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int minCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool minCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sequenceCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sequenceCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float branchCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool branchCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool maxCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool minCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleFiles")]
    public partial class ModuleFiles : EntityBase<ModuleFiles>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleFilesFile fileField;

        /// <summary>
        /// ModuleFiles class constructor
        /// </summary>
        public ModuleFiles()
        {
            this.fileField = new ModuleFilesFile();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleFilesFile File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleFilesFile")]
    public partial class ModuleFilesFile : EntityBase<ModuleFilesFile>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string fullPathField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullPath { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClasses")]
    public partial class ModuleClasses : EntityBase<ModuleClasses>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClass> classField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        /// <summary>
        /// ModuleClasses class constructor
        /// </summary>
        public ModuleClasses()
        {
            this.textField = new List<string>();
            this.classField = new List<ModuleClassesClass>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Class", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClass> Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClass")]
    public partial class ModuleClassesClass : EntityBase<ModuleClassesClass>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClassesClassSummary summaryField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string fullNameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClassesClassMethods methodsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName { get; set; }


        /// <summary>
        /// ModuleClassesClass class constructor
        /// </summary>
        public ModuleClassesClass()
        {
            this.methodsField = new ModuleClassesClassMethods();
            this.summaryField = new ModuleClassesClassSummary();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClassesClassSummary Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClassesClassMethods Methods
        {
            get
            {
                return this.methodsField;
            }
            set
            {
                this.methodsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassSummary")]
    public partial class ModuleClassesClassSummary : EntityBase<ModuleClassesClassSummary>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float sequenceCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool sequenceCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float branchCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool branchCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int maxCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool maxCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int minCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool minCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sequenceCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sequenceCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float branchCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool branchCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool maxCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool minCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethods")]
    public partial class ModuleClassesClassMethods : EntityBase<ModuleClassesClassMethods>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClassMethodsMethod> methodField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        /// <summary>
        /// ModuleClassesClassMethods class constructor
        /// </summary>
        public ModuleClassesClassMethods()
        {
            this.textField = new List<string>();
            this.methodField = new List<ModuleClassesClassMethodsMethod>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Method", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClassMethodsMethod> Method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethod")]
    public partial class ModuleClassesClassMethodsMethod : EntityBase<ModuleClassesClassMethodsMethod>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClassesClassMethodsMethodSummary summaryField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int metadataTokenField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClassesClassMethodsMethodFileRef fileRefField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClassesClassMethodsMethodSequencePoints sequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ModuleClassesClassMethodsMethodBranchPoints branchPointsField;

        //[EditorBrowsable(EditorBrowsableState.Never)]
        //private ModuleClassesClassMethodsMethodMethodPoint methodPointField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string visitedField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int cyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool cyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float sequenceCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool sequenceCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float branchCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool branchCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string isConstructorField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string isStaticField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string isGetterField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string isSetterField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MetadataToken { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string visited { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool cyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sequenceCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sequenceCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float branchCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool branchCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isConstructor { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isStatic { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isGetter { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isSetter { get; set; }


        /// <summary>
        /// ModuleClassesClassMethodsMethod class constructor
        /// </summary>
        public ModuleClassesClassMethodsMethod()
        {
            //this.methodPointField = new ModuleClassesClassMethodsMethodMethodPoint();
            this.branchPointsField = new ModuleClassesClassMethodsMethodBranchPoints();
            this.sequencePointsField = new ModuleClassesClassMethodsMethodSequencePoints();
            this.fileRefField = new ModuleClassesClassMethodsMethodFileRef();
            this.summaryField = new ModuleClassesClassMethodsMethodSummary();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClassesClassMethodsMethodSummary Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClassesClassMethodsMethodFileRef FileRef
        {
            get
            {
                return this.fileRefField;
            }
            set
            {
                this.fileRefField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClassesClassMethodsMethodSequencePoints SequencePoints
        {
            get
            {
                return this.sequencePointsField;
            }
            set
            {
                this.sequencePointsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleClassesClassMethodsMethodBranchPoints BranchPoints
        {
            get
            {
                return this.branchPointsField;
            }
            set
            {
                this.branchPointsField = value;
            }
        }

        //[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public ModuleClassesClassMethodsMethodMethodPoint MethodPoint
        //{
        //    get
        //    {
        //        return this.methodPointField;
        //    }
        //    set
        //    {
        //        this.methodPointField = value;
        //    }
        //}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodSummary")]
    public partial class ModuleClassesClassMethodsMethodSummary : EntityBase<ModuleClassesClassMethodsMethodSummary>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedSequencePointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedSequencePointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int numBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool numBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int visitedBranchPointsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool visitedBranchPointsFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float sequenceCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool sequenceCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private float branchCoverageField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool branchCoverageFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int maxCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool maxCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int minCyclomaticComplexityField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool minCyclomaticComplexityFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedSequencePoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedSequencePointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool numBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitedBranchPoints { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool visitedBranchPointsSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float sequenceCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sequenceCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float branchCoverage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool branchCoverageSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool maxCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minCyclomaticComplexity { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool minCyclomaticComplexitySpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodFileRef")]
    public partial class ModuleClassesClassMethodsMethodFileRef : EntityBase<ModuleClassesClassMethodsMethodFileRef>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uidSpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodSequencePoints")]
    public partial class ModuleClassesClassMethodsMethodSequencePoints : EntityBase<ModuleClassesClassMethodsMethodSequencePoints>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClassMethodsMethodSequencePointsSequencePoint> sequencePointField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        /// <summary>
        /// ModuleClassesClassMethodsMethodSequencePoints class constructor
        /// </summary>
        public ModuleClassesClassMethodsMethodSequencePoints()
        {
            this.textField = new List<string>();
            this.sequencePointField = new List<ModuleClassesClassMethodsMethodSequencePointsSequencePoint>();
        }

        [System.Xml.Serialization.XmlElementAttribute("SequencePoint", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClassMethodsMethodSequencePointsSequencePoint> SequencePoint
        {
            get
            {
                return this.sequencePointField;
            }
            set
            {
                this.sequencePointField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodSequencePointsSequencePoint")]
    public partial class ModuleClassesClassMethodsMethodSequencePointsSequencePoint : EntityBase<ModuleClassesClassMethodsMethodSequencePointsSequencePoint>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClassMethodsMethodSequencePointsSequencePointTrackedMethodRef> trackedMethodRefsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int vcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vcFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uspidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uspidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int ordinalField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool ordinalFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int offsetField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool offsetFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int slField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool slFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int scField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool scFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int elField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool elFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int ecField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool ecFieldSpecified;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vcSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uspid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uspidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ordinal { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ordinalSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int offset { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool offsetSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sl { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool slSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool scSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int el { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool elSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ec { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ecSpecified { get; set; }


        /// <summary>
        /// ModuleClassesClassMethodsMethodSequencePointsSequencePoint class constructor
        /// </summary>
        public ModuleClassesClassMethodsMethodSequencePointsSequencePoint()
        {
            this.textField = new List<string>();
            this.trackedMethodRefsField = new List<ModuleClassesClassMethodsMethodSequencePointsSequencePointTrackedMethodRef>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TrackedMethodRef", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClassMethodsMethodSequencePointsSequencePointTrackedMethodRef> TrackedMethodRefs
        {
            get
            {
                return this.trackedMethodRefsField;
            }
            set
            {
                this.trackedMethodRefsField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodSequencePointsSequencePointTrackedM" +
        "ethodRef")]
    public partial class ModuleClassesClassMethodsMethodSequencePointsSequencePointTrackedMethodRef : EntityBase<ModuleClassesClassMethodsMethodSequencePointsSequencePointTrackedMethodRef>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int vcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vcFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vcSpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodBranchPoints")]
    public partial class ModuleClassesClassMethodsMethodBranchPoints : EntityBase<ModuleClassesClassMethodsMethodBranchPoints>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClassMethodsMethodBranchPointsBranchPoint> branchPointField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        /// <summary>
        /// ModuleClassesClassMethodsMethodBranchPoints class constructor
        /// </summary>
        public ModuleClassesClassMethodsMethodBranchPoints()
        {
            this.textField = new List<string>();
            this.branchPointField = new List<ModuleClassesClassMethodsMethodBranchPointsBranchPoint>();
        }

        [System.Xml.Serialization.XmlElementAttribute("BranchPoint", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClassMethodsMethodBranchPointsBranchPoint> BranchPoint
        {
            get
            {
                return this.branchPointField;
            }
            set
            {
                this.branchPointField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodBranchPointsBranchPoint")]
    public partial class ModuleClassesClassMethodsMethodBranchPointsBranchPoint : EntityBase<ModuleClassesClassMethodsMethodBranchPointsBranchPoint>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClassMethodsMethodBranchPointsBranchPointTrackedMethodRef> trackedMethodRefsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int vcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vcFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uspidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uspidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int ordinalField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool ordinalFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int offsetField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool offsetFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string pathField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vcSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uspid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uspidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ordinal { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ordinalSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int offset { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool offsetSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path { get; set; }


        /// <summary>
        /// ModuleClassesClassMethodsMethodBranchPointsBranchPoint class constructor
        /// </summary>
        public ModuleClassesClassMethodsMethodBranchPointsBranchPoint()
        {
            this.textField = new List<string>();
            this.trackedMethodRefsField = new List<ModuleClassesClassMethodsMethodBranchPointsBranchPointTrackedMethodRef>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TrackedMethodRef", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClassMethodsMethodBranchPointsBranchPointTrackedMethodRef> TrackedMethodRefs
        {
            get
            {
                return this.trackedMethodRefsField;
            }
            set
            {
                this.trackedMethodRefsField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodBranchPointsBranchPointTrackedMetho" +
        "dRef")]
    public partial class ModuleClassesClassMethodsMethodBranchPointsBranchPointTrackedMethodRef : EntityBase<ModuleClassesClassMethodsMethodBranchPointsBranchPointTrackedMethodRef>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int vcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vcFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vcSpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodMethodPoint")]
    public partial class ModuleClassesClassMethodsMethodMethodPoint : EntityBase<ModuleClassesClassMethodsMethodMethodPoint>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ModuleClassesClassMethodsMethodMethodPointTrackedMethodRef> trackedMethodRefsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<string> textField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int vcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vcFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uspidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uspidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int ordinalField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool ordinalFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int offsetField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool offsetFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int slField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool slFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int scField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool scFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int elField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool elFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int ecField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool ecFieldSpecified;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vcSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uspid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uspidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ordinal { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ordinalSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int offset { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool offsetSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sl { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool slSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool scSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int el { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool elSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ec { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ecSpecified { get; set; }


        /// <summary>
        /// ModuleClassesClassMethodsMethodMethodPoint class constructor
        /// </summary>
        public ModuleClassesClassMethodsMethodMethodPoint()
        {
            this.textField = new List<string>();
            this.trackedMethodRefsField = new List<ModuleClassesClassMethodsMethodMethodPointTrackedMethodRef>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TrackedMethodRef", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ModuleClassesClassMethodsMethodMethodPointTrackedMethodRef> TrackedMethodRefs
        {
            get
            {
                return this.trackedMethodRefsField;
            }
            set
            {
                this.trackedMethodRefsField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleClassesClassMethodsMethodMethodPointTrackedMethodRef")]
    public partial class ModuleClassesClassMethodsMethodMethodPointTrackedMethodRef : EntityBase<ModuleClassesClassMethodsMethodMethodPointTrackedMethodRef>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int vcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vcFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vc { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vcSpecified { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuleTrackedMethod")]
    public partial class ModuleTrackedMethod : EntityBase<ModuleTrackedMethod>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int uidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uidFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int tokenField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool tokenFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string strategyField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uid { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool uidSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int token { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool tokenSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strategy { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

    }
}
