//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leem.Testify
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackedMethod
    {
        public TrackedMethod()
        {
            this.CoveredLines = new HashSet<CoveredLine>();
            this.UnitTests = new HashSet<UnitTest>();
        }
    
        public int UniqueId { get; set; }
        public string Name { get; set; }
        public string Strategy { get; set; }
        public int UnitTestId { get; set; }
    
        public virtual ICollection<CoveredLine> CoveredLines { get; set; }
        public virtual ICollection<UnitTest> UnitTests { get; set; }
    }
}
