//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leem.Testify
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestifyCEEntities : DbContext
    {
        public TestifyCEEntities()
            : base("name=TestifyCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CoveredLine> CoveredLines { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<TestProject> TestProjects { get; set; }
        public DbSet<TrackedMethod> TrackedMethods { get; set; }
        public DbSet<UnitTest> UnitTests { get; set; }
    }
}
