//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leem.Testify.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTest
    {
        public UnitTest()
        {
            this.TrackedMethods = new HashSet<TrackedMethod>();
        }
    
        public int UnitTestId { get; set; }
        public string TestProjectUniqueName { get; set; }
        public bool IsSuccessful { get; set; }
        public Nullable<int> MetadataToken { get; set; }
        public string TestMethodName { get; set; }
        public Nullable<int> NumberOfAsserts { get; set; }
        public bool Executed { get; set; }
        public string Result { get; set; }
        public string AssemblyName { get; set; }
        public string LastRunDatetime { get; set; }
        public string LastSuccessfulRunDatetime { get; set; }
        public string TestDuration { get; set; }
    
        public virtual TestProject TestProject { get; set; }
        public virtual ICollection<TrackedMethod> TrackedMethods { get; set; }
    }
}
