//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CoverageSession{
    
    private string numSequencePointsField;
    
    private string visitedSequencePointsField;
    
    private string numBranchPointsField;
    
    private string visitedBranchPointsField;
    
    private string sequenceCoverageField;
    
    private string branchCoverageField;
    
    private string maxCyclomaticComplexityField;
    
    private string minCyclomaticComplexityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numSequencePoints {
        get {
            return this.numSequencePointsField;
        }
        set {
            this.numSequencePointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visitedSequencePoints {
        get {
            return this.visitedSequencePointsField;
        }
        set {
            this.visitedSequencePointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numBranchPoints {
        get {
            return this.numBranchPointsField;
        }
        set {
            this.numBranchPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visitedBranchPoints {
        get {
            return this.visitedBranchPointsField;
        }
        set {
            this.visitedBranchPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sequenceCoverage {
        get {
            return this.sequenceCoverageField;
        }
        set {
            this.sequenceCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string branchCoverage {
        get {
            return this.branchCoverageField;
        }
        set {
            this.branchCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxCyclomaticComplexity {
        get {
            return this.maxCyclomaticComplexityField;
        }
        set {
            this.maxCyclomaticComplexityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minCyclomaticComplexity {
        get {
            return this.minCyclomaticComplexityField;
        }
        set {
            this.minCyclomaticComplexityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CoverageSession {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Modules", typeof(CoverageSessionModules), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("Summary", typeof(Summary))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModules {
    
    private CoverageSessionModulesModule[] moduleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Module", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CoverageSessionModulesModule[] Module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModule {
    
    private string fullNameField;
    
    private string moduleNameField;
    
    private Summary[] summaryField;
    
    private CoverageSessionModulesModuleFilesFile[][] filesField;
    
    private CoverageSessionModulesModuleClassesClass[][] classesField;
    
    private string skippedDueToField;
    
    private string hashField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ModuleName {
        get {
            return this.moduleNameField;
        }
        set {
            this.moduleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Summary")]
    public Summary[] Summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("File", typeof(CoverageSessionModulesModuleFilesFile), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CoverageSessionModulesModuleFilesFile[][] Files {
        get {
            return this.filesField;
        }
        set {
            this.filesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Class", typeof(CoverageSessionModulesModuleClassesClass), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CoverageSessionModulesModuleClassesClass[][] Classes {
        get {
            return this.classesField;
        }
        set {
            this.classesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string skippedDueTo {
        get {
            return this.skippedDueToField;
        }
        set {
            this.skippedDueToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleFilesFile {
    
    private string uidField;
    
    private string fullPathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fullPath {
        get {
            return this.fullPathField;
        }
        set {
            this.fullPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleClassesClass {
    
    private string fullNameField;
    
    private Summary[] summaryField;
    
    private CoverageSessionModulesModuleClassesClassMethodsMethod[][] methodsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Summary")]
    public Summary[] Summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Method", typeof(CoverageSessionModulesModuleClassesClassMethodsMethod), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CoverageSessionModulesModuleClassesClassMethodsMethod[][] Methods {
        get {
            return this.methodsField;
        }
        set {
            this.methodsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleClassesClassMethodsMethod {
    
    private string metadataTokenField;
    
    private string nameField;
    
    private Summary[] summaryField;
    
    private CoverageSessionModulesModuleClassesClassMethodsMethodFileRef[] fileRefField;
    
    private CoverageSessionModulesModuleClassesClassMethodsMethodSequencePointsSequencePoint[][] sequencePointsField;
    
    private CoverageSessionModulesModuleClassesClassMethodsMethodBranchPointsBranchPoint[][] branchPointsField;
    
    private CoverageSessionModulesModuleClassesClassMethodsMethodMethodPoint[] methodPointField;
    
    private string visitedField;
    
    private string cyclomaticComplexityField;
    
    private string sequenceCoverageField;
    
    private string branchCoverageField;
    
    private string isConstructorField;
    
    private string isStaticField;
    
    private string isGetterField;
    
    private string isSetterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MetadataToken {
        get {
            return this.metadataTokenField;
        }
        set {
            this.metadataTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Summary")]
    public Summary[] Summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CoverageSessionModulesModuleClassesClassMethodsMethodFileRef[] FileRef {
        get {
            return this.fileRefField;
        }
        set {
            this.fileRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SequencePoint", typeof(CoverageSessionModulesModuleClassesClassMethodsMethodSequencePointsSequencePoint), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CoverageSessionModulesModuleClassesClassMethodsMethodSequencePointsSequencePoint[][] SequencePoints {
        get {
            return this.sequencePointsField;
        }
        set {
            this.sequencePointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("BranchPoint", typeof(CoverageSessionModulesModuleClassesClassMethodsMethodBranchPointsBranchPoint), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CoverageSessionModulesModuleClassesClassMethodsMethodBranchPointsBranchPoint[][] BranchPoints {
        get {
            return this.branchPointsField;
        }
        set {
            this.branchPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MethodPoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CoverageSessionModulesModuleClassesClassMethodsMethodMethodPoint[] MethodPoint {
        get {
            return this.methodPointField;
        }
        set {
            this.methodPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visited {
        get {
            return this.visitedField;
        }
        set {
            this.visitedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cyclomaticComplexity {
        get {
            return this.cyclomaticComplexityField;
        }
        set {
            this.cyclomaticComplexityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sequenceCoverage {
        get {
            return this.sequenceCoverageField;
        }
        set {
            this.sequenceCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string branchCoverage {
        get {
            return this.branchCoverageField;
        }
        set {
            this.branchCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isConstructor {
        get {
            return this.isConstructorField;
        }
        set {
            this.isConstructorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isStatic {
        get {
            return this.isStaticField;
        }
        set {
            this.isStaticField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isGetter {
        get {
            return this.isGetterField;
        }
        set {
            this.isGetterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isSetter {
        get {
            return this.isSetterField;
        }
        set {
            this.isSetterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleClassesClassMethodsMethodFileRef {
    
    private string uidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleClassesClassMethodsMethodSequencePointsSequencePoint {
    
    private string vcField;
    
    private string uspidField;
    
    private string ordinalField;
    
    private string offsetField;
    
    private string slField;
    
    private string scField;
    
    private string elField;
    
    private string ecField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vc {
        get {
            return this.vcField;
        }
        set {
            this.vcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uspid {
        get {
            return this.uspidField;
        }
        set {
            this.uspidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ordinal {
        get {
            return this.ordinalField;
        }
        set {
            this.ordinalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sl {
        get {
            return this.slField;
        }
        set {
            this.slField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sc {
        get {
            return this.scField;
        }
        set {
            this.scField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string el {
        get {
            return this.elField;
        }
        set {
            this.elField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ec {
        get {
            return this.ecField;
        }
        set {
            this.ecField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleClassesClassMethodsMethodBranchPointsBranchPoint {
    
    private string vcField;
    
    private string uspidField;
    
    private string ordinalField;
    
    private string offsetField;
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vc {
        get {
            return this.vcField;
        }
        set {
            this.vcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uspid {
        get {
            return this.uspidField;
        }
        set {
            this.uspidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ordinal {
        get {
            return this.ordinalField;
        }
        set {
            this.ordinalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CoverageSessionModulesModuleClassesClassMethodsMethodMethodPoint {
    
    private string vcField;
    
    private string uspidField;
    
    private string ordinalField;
    
    private string offsetField;
    
    private string slField;
    
    private string scField;
    
    private string elField;
    
    private string ecField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vc {
        get {
            return this.vcField;
        }
        set {
            this.vcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uspid {
        get {
            return this.uspidField;
        }
        set {
            this.uspidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ordinal {
        get {
            return this.ordinalField;
        }
        set {
            this.ordinalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sl {
        get {
            return this.slField;
        }
        set {
            this.slField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sc {
        get {
            return this.scField;
        }
        set {
            this.scField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string el {
        get {
            return this.elField;
        }
        set {
            this.elField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ec {
        get {
            return this.ecField;
        }
        set {
            this.ecField = value;
        }
    }
}
