// <auto-generated />
namespace Leem.Testify.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_Modules_Classes_Methods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Modules_Classes_Methods));
        
        string IMigrationMetadata.Id
        {
            get { return "201403301750396_Added_Modules_Classes_Methods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
